- lang_qc/main.py
> Remove redirect from root to docs.

- lang_qc/endpoints/pacbio_run.py
> Make well endpoint more RESTful.

- .github/workflows/test.yml
- pyproject.toml
The source folder is not `npg_langqc` so the source was not automatically found by poetry-core.
Also adds a check in CI that the package installs properly with `pip install .`
> Fix broken packaging.

- README.md
- lang_qc/main.py
This is a minimal solution to let us have CORS properly configured, and deployed. It doesn't fix anything from #6, actually it reproduces the issue (the issue is only present if the CORS middleware is used).
> Add minimal solution for configurable CORS-enabled origins.

- README.md
Add instructions and improve formatting of `README.md`.
> Add instructions to run with Docker.

- .flake8
- .github/workflows/test.yml
- lang_qc/db/mlwh_connection.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/fixtures/inbox_data.py
- tests/test_lang_qc.py
- tests/testdb.ini
Sets up some testing infrastructure for endpoints that fetch things in the mlwh. 
Based off the testing done in wtsi-npg/ml-warehouse-python, needs a MySQL DB (in CI, MySQL container). Unfortunately, we can't really use a SQLite DB for testing as the ml-warehouse schema doesn't work with it.
The tests are simple in this PR, but hopefully this will help add tests for the new endpoints to add.
> Setup some initial testing.

- lang_qc/db/utils.py
- lang_qc/endpoints/inbox.py
- lang_qc/models/inbox_models.py
- tests/conftest.py
- tests/fixtures/inbox_data.py
- tests/test_filtered_inbox.py
Draft for now as tests are to come, building on #21.
> Add filtered inbox endpoint.

- lang_qc/util/qc_state_helpers.py
- poetry.lock
- pyproject.toml
Switch dependency to wtsi-npg/npg_id_generation, and update lockfile.
> Switch dependency to wtsi-npg/npg_id_generation.

- lang_qc/db/mlwh_connection.py
- lang_qc/db/qc_connection.py
- lang_qc/db/utils.py
- lang_qc/endpoints/qc_state.py
- lang_qc/models/qc_state_models.py
- lang_qc/util/qc_state_helpers.py
- tests/fixtures/inbox_data.py
- tests/test_assign_qc_state.py
- tests/test_claim_well.py
Separate claiming and assigning states, enforcing the rules laid out in #31.
Supercedes #24.
> Separate claiming and assigning states.

- README.md
- docker-compose.dev.yml
- docker-compose.yml
- docker/proxy/000-default.conf.dev
- docker/proxy/Dockerfile
- frontend/Dockerfile
There is an issue with websocket connections not being passed through from browser - proxy - vite. But that seems to only break the automatic browser reloading on changes. Hitting reload on the browser is an easy workaround.
> Set up hot-reloading of the frontend in the development compose.

- .github/workflows/lint.yml
- alembic/env.py
- alembic/versions/50eb2dc8f2cd_extend_username_column.py
- alembic/versions/67fddcef9a89_first_revision_of_qc_db_schema.py
- lang_qc/db/mlwh_connection.py
- lang_qc/db/qc_connection.py
- lang_qc/db/qc_schema.py
- lang_qc/endpoints/inbox.py
- lang_qc/endpoints/pacbio_run.py
- lang_qc/endpoints/qc_state.py
- lang_qc/models/pacbio_run_models.py
- lang_qc/router.py
- lang_qc/util/qc_state_helpers.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/fixtures/inbox_data.py
- tests/test_assign_qc_state.py
- tests/test_claim_well.py
- tests/test_filtered_inbox.py
- tests/test_lang_qc.py
Introduce [isort](https://pycqa.github.io/isort/) to sort imports, and run it as a check in CI.
> Sort imports using isort

- frontend/src/components/__tests__/QcView.spec.js
- frontend/src/utils/langqc.js
- frontend/src/views/RunView.vue
Adapt the "RunWell" view to load the "QC view" on click. Lacks enough testing, but I lack the skills.
> Working clone of prototype

- frontend/src/components/QcView.vue
- lang_qc/models/pacbio_run_models.py
- tests/fixtures/inbox_data.py
- tests/test_lang_qc.py
Developed on top of https://github.com/wtsi-npg/npg_langqc/pull/48
> Simplify run feed and display library type

- lang_qc/endpoints/config.py
- lang_qc/endpoints/pacbio_well.py
- lang_qc/models/inbox_models.py
- lang_qc/models/qc_flow_status.py
- tests/test_lang_qc.py
Disambiguation of QC flow statuses from QC states of individual wells.
> Serve info about known QC flow statuses.

- lang_qc/db/utils.py
> Added a comment to clarify the inbox query

- docker/proxy/000-default.conf
- docker/proxy/000-default.conf.dev
- frontend/src/utils/__tests__/langqc.spec.js
- frontend/src/utils/langqc.js
- frontend/src/views/RunView.vue
- lang_qc/main.py
Also clean up residual URL mess from JS code.
> Change apache routing to put all API calls under a single proxy rule

- frontend/package.json
- frontend/src/main.js
- frontend/src/utils/__tests__/langqc.spec.js
- frontend/src/utils/langqc.js
- frontend/src/views/RunView.vue
- tests/fixtures/inbox_data.py
Styling is copy-pasted. No tests, no data to prove that a QC state is rendered correctly... Great!
> Crude tabs

- lang_qc/db/helper/well.py
- lang_qc/endpoints/config.py
- tests/fixtures/inbox_data.py
- tests/test_lang_qc.py
Built on top of https://github.com/wtsi-npg/npg_langqc/pull/74
> States in config

- lang_qc/db/utils.py
- lang_qc/util/auth.py
- misc/load_qc_data4demo.py
The script now uses the new API for well QC.
Unused functions deleted.
The function for retrieving a user is moved to the auth package.
> Refactored the script for loading demo data to the db.

- lang_qc/models/pacbio/qc_data.py
- tests/endpoints/test_filtered_wells.py
Change alters values to match those found in sequencescape.
> Change divisor for p-values from "productive zmws" to sum of all p-values

- alembic/versions/0a3a2726e378_index_qc_state_date_column.py
Added indexes to qc_data and qc_data_dict tables
to speed up batch retrieval of sorted data.
> Optimised QC outcomes retrieval.

- lang_qc/db/helper/well.py
- lang_qc/db/helper/wells.py
- lang_qc/endpoints/pacbio_well.py
- lang_qc/models/pacbio/well.py
- tests/test_wh_access_classes.py
Created a reusable method for populating run tracking info into the well model thus removing the current and future code duplication.
Removed a special class for retrieving the  mlwh row for a single well, moved the methods from the class into the db helper class and used them where previously duplicate db queries were present.
> Removed code duplication.

- docs/qc_schema_explained.md
As per gist previously discussed
> Textual description of how the QC schema works

- README.md
- frontend/Dockerfile
- frontend/src/components/QcView.vue
- frontend/src/components/__tests__/QcView.spec.js
Amend the README file to instruct how to create the .env file for VITE.
> Read the SMRT Link port from the .env file.

- frontend/package.json
- frontend/src/components/__tests__/QcControls.spec.js
- frontend/src/components/__tests__/QcWidget.spec.js
- frontend/src/stores/__tests__/focusWell.spec.js
- frontend/src/stores/focusWell.js
- frontend/src/views/RunView.vue
Also update vitest version to force support for stubEnv()
> Get newest QC state from well detail request instead of run table.

- frontend/src/router/index.js
- frontend/src/utils/__tests__/url.spec.js
- frontend/src/utils/url.js
- frontend/src/views/RunView.vue
- frontend/src/views/__tests__/RunView.spec.js
Not happy with the code, but it seems to work as desired. Tests completely ignored
> Router-controlled page state.

- frontend/src/components/WellTable.vue
- frontend/src/components/__tests__/WellTable.spec.js
- frontend/src/router/index.js
- frontend/src/utils/__tests__/url.spec.js
- frontend/src/utils/url.js
- frontend/src/views/RunView.vue
- frontend/src/views/__tests__/RunView.spec.js
> Standalone runtable component

- frontend/src/views/WellsByStatus.vue
The content is incorrect for all but the active tab. Resolves NPG-1157
> Stop rendering tabs when they're not active.

- CHANGELOG.md
- frontend/package.json
- frontend/src/App.vue
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/views/WellsByRun.vue
- frontend/src/views/__tests__/WellsByRun.spec.js
- frontend/src/views/__tests__/WellsByStatus.spec.js
Crude... Had difficulty disabling the alternate search mode when it doesn't make any sense.
> Allow searching for multiple runs.

- README.md
- docs/background.md
- frontend/README.md
Remove devopsy instructions from here, in favour of langqc_deploy.
Provide some background for the application
> Docs update

- CHANGELOG.md
- frontend/src/components/QcView.vue
- frontend/src/components/WellTable.vue
- frontend/src/components/__tests__/QcView.spec.js
- frontend/src/components/__tests__/WellTable.spec.js
- frontend/src/views/__tests__/WellsByRun.spec.js
- frontend/src/views/__tests__/WellsByStatus.spec.js
- lang_qc/models/pacbio/well.py
- tests/endpoints/test_filtered_wells.py
- tests/endpoints/test_single_well_qc_details.py
- tests/endpoints/test_wells4run.py
- tests/fixtures/well_data.py
- tests/test_pac_well_full.py
Include instrument metadata in data for inbox and QC View
> Instrument name API support

- lang_qc/db/helper/wells.py
- lang_qc/db/mlwh_schema.py
- tests/endpoints/test_filtered_wells.py
- tests/endpoints/test_single_well_qc_details.py
- tests/endpoints/test_wells4run.py
- tests/fixtures/well_data.py
- tests/test_pac_well_full.py
Added the plate_number column to relevant tables, see https://github.com/wtsi-npg/ml_warehouse/pull/216 for changes to the production database.
Updated test data.
> Updated mlwh ORM.

- poetry.lock
- pyproject.toml
... to get support for plate numbers.
Minor upgrades to other packages as well as suggested by poetry.
> Upgraded npg_id_generation to 4.0.0

- alembic/README.md
- alembic/versions/36952df5b8ba_add_ability_to_record_plate_number.py
- lang_qc/db/qc_schema.py
Created columns for the third sub-product attribute, making it optional. Created an entry for the plate attribute for PacBio products.
Created the alembic migration for the LangQC database
change (both schema and dict) and updated the ORM.
> Changed the db schema to record plate number.

- frontend/src/App.vue
- frontend/vite.config.js
Also a pass of JS linting on App.vue
> Use Vite to provide package version for display on QC interface

- CHANGELOG.md
- lang_qc/db/helper/well.py
- lang_qc/db/helper/wells.py
- lang_qc/endpoints/pacbio_well.py
- lang_qc/main.py
- lang_qc/models/pacbio/experiment.py
- lang_qc/models/pacbio/qc_data.py
- lang_qc/models/pacbio/well.py
- lang_qc/models/pager.py
- lang_qc/models/qc_state.py
- lang_qc/util/type_checksum.py
- poetry.lock
- pyproject.toml
- tests/endpoints/test_assign_qc_state.py
- tests/endpoints/test_claim_well.py
- tests/endpoints/test_dump_qc_states.py
- tests/endpoints/test_single_well_qc_details.py
- tests/fixtures/inbox_data.py
- tests/fixtures/well_data.py
- tests/test_checksum_type.py
Not a pretty upgrade process :/
> Upgrade pydantic and fastapi to new versions

- frontend/package.json
Pending an inspection on the dev server UI
> Pinned element-plus JS package to 2.4.4 

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Also upgraded alembic to 1.13.0 or later.
Regenerated poetry.lock file.
> Upgraded dev dependency npg_id_generation to 5.0.1

- CHANGELOG.md
- alembic/README.md
- alembic/versions/2.0.0_drop_json_properties_column.py
- lang_qc/db/qc_schema.py
Ths column is no longer populated.
Updated ORM for LangQC database.
Updated instructions for creating alembic migration script.
> Dropped column 'properties' from sub_product db table.

- misc/validate_id_generator.py
All PacBio mlwh records are inspected, the ID is generated from scratch and compared to the one stored in the database.
> Added a scripts to validate ID generator

- lang_qc/db/mlwh_schema.py
See https://github.com/wtsi-npg/ml_warehouse/pull/228
> Following a column deletion, updated mlwh ORM.

- lang_qc/db/helper/wells.py
- lang_qc/endpoints/pacbio_well.py
- lang_qc/models/pacbio/qc_data.py
- tests/test_pac_bio_qc_data_well.py
Return 409 status in case of incomplete or missing LIMS data.
Do not error if the metrics cannot be computed since the client does not necessary know whether it is
appropriate to request this metrics.
> Moved QCPoolMetrics model generation to the model itself.

- lang_qc/models/pacbio/qc_data.py
- tests/endpoints/test_single_well_qc_details.py
- tests/test_pac_bio_qc_data_well.py
`statistics.stdev` is a sample standard deviation. We need the population standard deviation because we are looking at the entire pool.
> Coeff variation fix

- CHANGELOG.md
- frontend/src/components/WellTable.vue
- frontend/src/components/__tests__/WellTable.spec.js
- frontend/src/views/WellsByStatus.vue
- frontend/src/views/__tests__/WellsByStatus.spec.js
> Allow clickable run names in Well table to jump to wells-by-run
