wtsi-npg/npg_langqc

- .github/workflows/test.yml
- lang_qc/db/qc_connection.py
- lang_qc/db/qc_schema.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/testdb.ini
`lang_qc/db/qc_connection.py` is generated by `sqlacodegen`([version 3.0.0rc1](https://github.com/agronholm/sqlacodegen/releases/tag/3.0.0rc1)), with the copyright notice added on top. `sqlacodegen` was run against the schema defined in #4, specifically from commit <https://github.com/wtsi-npg/npg_langqc/pull/4/commits/e381b672b99385e02add8b76a9fb4412d561fa5e>, deployed on a MySQL 8.0 container. The file isn't formatted after generation, so flake8 and black are set to ignore it.
Two options for this file:
- use it as a starting point to define the schema with SQLAlchemy models. We could then customise the SQLAlchemy models with relationships that `sqlacodegen` doesn't reflect in the most convenient way, without needing to maintain an extra layer on top of the `sqlacodegen` output. We …
> Add QC DB schema and connection.

- poetry.lock
- pyproject.toml
`ml-warehouse-python` `1.0.0` was released, switch to it and update the lockfile.
> Switch ml-warehouse-python dependency to 1.0.0 release.

- docker-compose.yml
- docker/proxy/Dockerfile
- docker/proxy/start.sh
Change how `apache2` is run in the proxy service container, and get it to receive a `SIGWINCH` for a graceful stop.
Add dependencies between the services for proper ordering of startup and shutdown.
> Gracefully stop the proxy

- .github/workflows/publish-docker.yml
In #29, the main `Dockerfile` got two separate targets. So since then, the last target in the `Dockerfile` is the one which was being published, in our case `development`.
This PR sets the target to `production` which is probably what we actually want to publish.
> Specify production image in github workflow.

- frontend/Dockerfile
- frontend/httpd.conf
When serving the static built Vue app, there is no nodeJS server
to do the routing dynamically. The vue router would not be there
to intercept the request and serve the appropriate page. Instead,
vue-router's documentation suggests to make the web server fallback
to serving /index.html, and then the SPA will render the appropriate
page.
See https://router.vuejs.org/guide/essentials/history-mode.html#apache
It might be useful to add a 404 handler in the Vue app, see
https://router.vuejs.org/guide/essentials/history-mode.html#caveat
The `frontend/httpd.conf` file is the default one from the `httpd:alpine` image, with the `FallbackResource /index.html` line appended. This approach was suggested by [the httpd Docker image docs](https://hub.docker.com/_/httpd), although I suppose in this case …
> Fix 404s on loading dynamic vue routes.

- lang_qc/db/helper/well.py
The default dates were assigned at the time of
loading the code into memory, which, in the context of a web application, where the loaded code persists across multiple requests, results in the same dates in the past being used.
> Fixed a bug in dates generation for qc states

- .github/workflows/lint.yml
- docker-compose.yml
- docker/proxy/000-default.conf
- docker/proxy/000-default.conf.dev
- frontend/Dockerfile
- Remove the last remains of an old hack to make the front end direct API requests to the back end.
- Add ESLint to the github workflow
- Reduce the aggressiveness of the default OICD timeout to reduce hair-tearing.
- Update dev apache conf to match production
- Reduce frontend docker image size by half by switching over to Alpine
> Decrufting

- tests/conftest.py
- tests/fixtures/inbox_data.py
- tests/fixtures/qc_db_basic_data.py
- tests/test_qc_state_maintenance.py
Set the scope of fixtures to 'module' or 'package' where possible. The fixtures that create databases are now run once per module (test file). Sourcing of credentials for databases is done once per the pytest run ('package' scope).
Added the teardown section (after the 'yield' statement) to fixtures with the 'function' scope (the default scope of the pytest fixtures). The teardown section deletes all data that the fixture loaded to the databases.
Dropped altering the settings of the mlwh database at the stage of creating the schema. Instead, foreign keys constraints are now dropped at the teardown section and reinstated once data deletion is done.
> Reduced run time for tests.

- README.md
- lang_qc/db/helper/well.py
- misc/backfill_qc_states.py
- poetry.lock
- pyproject.toml
Past QC decisions are available in a spreadsheet.
The script attempts to find sensible data in this spreadsheet and creates new QC outcomes in LangQC database.
> Added a script for back-filling qc data.

- lang_qc/db/helper/well.py
- tests/endpoints/test_claim_well.py
- tests/test_qc_state_maintenance.py
Avoids potential container UTC vs host DST settings. Let the database always be right.
> Stop generating timestamps in python wherever possible.

- tests/fixtures/inbox_data.py
- tests/fixtures/well_data.py
Tests fixed in preparetion for
https://github.com/wtsi-npg/ml_warehouse/pull/208 and https://github.com/wtsi-npg/ml-warehouse-python/pull/91, when product ids will become not nullable.
Tested against https://github.com/wtsi-npg/ml-warehouse-python/pull/91
> Ensured product ids are defined in test fixtures.

- frontend/src/components/__tests__/QcWidget.spec.js
"aria-disabled" becomes "ariadisabled" with latest release in NPM. Change to checking for a different disabled attribute
> Later el-plus rendering of <button> seems to have a typo

- lang_qc/db/helper/wells.py
- lang_qc/endpoints/pacbio_well.py
- lang_qc/models/pacbio/well.py
- lang_qc/models/pager.py
- tests/endpoints/test_filtered_wells.py
- tests/test_wells4status_retrieval.py
qc_flow_status key was a part of the response to a request to fetch wells for a particular QC flow status. This key is not being used by the front end code. Its presence makes the response model less generic, i.e. not usable for requests that are not associated with any particular QC flow status.
> Removed qc_flow_status key from JSON response.

- lang_qc/db/helper/wells.py
- lang_qc/db/mlwh_schema.py
- lang_qc/models/pacbio/experiment.py
- lang_qc/models/pacbio/qc_data.py
- lang_qc/models/pacbio/well.py
- misc/backfill_qc_states.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/data/mlwh_pb_run_92/100-Sample.yml
- tests/data/mlwh_pb_run_92/100-Study.yml
- tests/endpoints/test_single_well_qc_details.py
- tests/fixtures/inbox_data.py
- tests/fixtures/utils.py
- tests/fixtures/well_data.py
- tests/test_pac_bio_experiment.py
- tests/test_pac_well_full.py
- tests/test_wh_data_retrieval_pb.py
Copied a few classes we need from the external
ml_warehouse package to lang_qc.db.mlwh_schema.
Reduced the number of imports to the types that
are actually needed. Reduced the number of mapped
columns for the study and sample tables to columns we are or might be using.
> Added local ORM classes for mlwh database.

- lang_qc/db/mlwh_connection.py
- lang_qc/db/qc_connection.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
The warnings describe situations where users were relying on implicit session-adds. It's only a problem if we were not adding our new items to the session by hand. We do, so it's a non-issue. Everything seems to work both in test and the real.
> SQLAlchemy compatibility warnings are non-entities. Update deps and remove future flags

- lang_qc/db/helper/well.py
- lang_qc/db/helper/wells.py
- lang_qc/db/qc_schema.py
- pyproject.toml
- tests/fixtures/inbox_data.py
- tests/test_qc_state_maintenance.py
No need to reference the linker table anywhere. See `sub_products` relationship. Schema file reformatted with black now we're not expecting to regenerate it.
> Use many-to-many relationship in sqlalchemy.

- frontend/src/utils/metrics.js
- lang_qc/models/pacbio/qc_data.py
- tests/endpoints/test_single_well_qc_details.py
No unit tests were harmed in this experiment.
Needs units for the concentration description, and may need numeric scaling/rounding
> Display loading concentrations

- tests/endpoints/test_config.py
Used more comprehensive test fixtures.
Renamed the test file to reflect the purpose of the test.
Removed the test that tested FastAPI.
> Updated tests for the config endpoint.

- tests/fixtures/well_data.py
Stopped using one of the application's classes
to load QC states to the test database. A close
cohesion between the test fixtures and the code
under the test was making it difficult to test
any potential regression when refactoring the
code.
> Extended QC data fixtures with plate_number

- lang_qc/db/helper/well.py
- lang_qc/db/helper/wells.py
- lang_qc/endpoints/pacbio_well.py
- tests/endpoints/test_assign_qc_state.py
- tests/endpoints/test_claim_well.py
- tests/endpoints/test_filtered_wells.py
- tests/fixtures/well_data.py
- tests/test_pac_bio_qc_data_well.py
- tests/test_pac_well_full.py
- tests/test_pb_wells_factory.py
- tests/test_qc_state_maintenance.py
- tests/test_wh_data_retrieval_pb.py
Depends on https://github.com/wtsi-npg/npg_langqc/pull/171
Endpoint URLs are changed. Product ID, but no other
identifier, is embedded into the URLs. The database
helper is changed to reflect this change. It is also
extended to accommodate an extra identifier - the
plate number. Mapping of product IDs to run name,
well label and plate number is done via the mlwh,
records therefore creating QC records for entities
that are not present in mlwh becomes impossible.
> Claim and update QC by product ID

- CHANGELOG.md
- lang_qc/db/helper/qc.py
- lang_qc/db/helper/wells.py
- lang_qc/endpoints/product.py
- lang_qc/models/pacbio/well.py
- tests/test_qc_state_retrieval.py
In future lang_qc/db/helper/qc.py will be used as a platform- independent retrieved of QC states for a single product or lists of products. The current designed is changed to pure functional since no state is associated with the proposed functionality.
Static type annotations are used to help with understanding input and output data.
All functions apart from the one used externally are converted to private. Tests are added for the only remaining public function.
A bug (incorrect implementation for the sequencing_outcomes_only flag) is fixed.
The module converted to pure functional
> QC states retrieval refactored, bug fixed.

- CHANGELOG.md
- lang_qc/db/helper/wells.py
- tests/fixtures/well_data.py
- tests/test_wh_data_retrieval_pb.py
Increased the look-back period for the inbox query from 4 weeks to 12 weeks. Added a preliminary filtering by the QC state, which is now available in mlwh. Since the mlwh QC state might not be up-to-date, a final check against the LangQC database is retained.
> Increased the look-back period for inbox.

- CHANGELOG.md
- lang_qc/db/helper/wells.py
- lang_qc/models/qc_flow_status.py
- tests/endpoints/test_config.py
- tests/endpoints/test_filtered_wells.py
- tests/fixtures/well_data.py
- tests/test_pb_wells_factory.py
Built on top of https://github.com/wtsi-npg/npg_langqc/pull/185
> Upcoming tab

- CHANGELOG.md
- alembic/README.md
- alembic/versions/3814003a709a_make_column_properties_nullable.py
- lang_qc/db/helper/well.py
- lang_qc/db/qc_schema.py
- pyproject.toml
- tests/fixtures/inbox_data.py
- tests/fixtures/well_data.py
The properties column of the LangQC sub_product database table is made nullable. The correctness of data in this column is no longer guaranteed, the column will be dropped in future.
> Made 'properties' column nullable.

- lang_qc/db/mlwh_schema.py
See https://github.com/wtsi-npg/ml_warehouse/commit/12d0c9452cc72a2d258776272ca7bbcd4f3a43db
> Update PacBioProductMetrics definition to include new per-product metrics

- alembic/versions/2.1.0_extend_qc_state_dict.py
- lang_qc/db/helper/wells.py
- lang_qc/endpoints/config.py
- tests/endpoints/test_config.py
- tests/endpoints/test_dump_qc_states.py
- tests/endpoints/test_filtered_wells.py
- tests/endpoints/test_wells4run.py
- tests/fixtures/well_data.py
- tests/test_pb_wells_factory.py
- tests/test_qc_state_retrieval.py
This state will be assigned to wells when the
outcome of the QC assessment depends on liasing
with a third party. The existing 'On hold' state
will be used for flagging internal investigations.
As fas as QC statuses and workflow is concerned,
the new state is handled in the same way as the
existing 'On hold' state.
> Introduced 'On hold external' QC state.

- frontend/Dockerfile
- frontend/package.json
Allows container run with `docker-compose --env-file $HOME/.env -f docker-compose.yml -f docker-compose.dev.yml up -d` to correctly ship unminified source to the browser.
> Fix the way vite runs in dev mode so that browser tools work

- frontend/src/components/QcView.vue
- frontend/src/stores/focusWell.js
- frontend/src/views/WellsByRun.vue
- frontend/src/views/__tests__/WellsByRun.spec.js
- lang_qc/endpoints/pacbio_well.py
- lang_qc/models/pacbio/qc_data.py
Stop sending response data when there are no products in `mlwh.pac_bio_product_metrics`, don't try to calculate stats on n=1, and make the client only request pool stats when we believe we have multiplexing.
> Bug fixes to pool table

- frontend/src/App.vue
- frontend/src/components/PoolStats.vue
Highlighting desired reads per sample with pre-existing table colourings.
I tried bold text, but it didn't look right as the only bold on the page
> Lift colours to app-level CSS so we can reuse in more tables.
